package org.ucenter.web.dao;

import java.util.List;
import org.ucenter.web.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Nov 11 22:21:32 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Nov 11 22:21:32 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Nov 11 22:21:32 CST 2020
     */
    User selectByPrimaryKey(Integer id);

    User selectByKeyword(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Nov 11 22:21:32 CST 2020
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Nov 11 22:21:32 CST 2020
     */
    int updateByPrimaryKey(User record);
}